CREATE TABLE history (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    name VARCHAR(50) NOT NULL,
    bidPrice FLOAT DEFAULT NULL,
    productName VARCHAR(255),
    item_id INTEGER DEFAULT NULL,
    PRIMARY KEY (id),
FOREIGN KEY (item_id) REFERENCES item(id) 
);
